[package]
name = "rwebc-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = { version = "*"}
clap = { version = "*", features = ["derive"] }
simple_logger = "*"
log = { version = "*" }
serde = { version = "*", features = ["derive"] }

[build-dependencies]
winres = "0.1"