[workspace]
members = [ "cert-key-file", "common", "proxy-change-header","rwebc", "rwebc-demo", "rwebs"]

resolver = "2"

[profile.release]
debug = true
panic = 'abort'
strip = true
opt-level = 'z'
lto=true
codegen-units = 1
