[workspace]
members = [ "cert-key-file", "common", "proxy-change-header","rwebc", "rwebc-demo", "rwebs"]

resolver = "2"

[profile.release]
debug = false
panic = 'abort'
strip = true
#strip = "symbols"
opt-level = 'z'
lto=true
#lto = "fat"
codegen-units = 1