[package]
name = "rwebs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "*",features = ["rt","macros","rt-multi-thread","sync","io-util"] }
simple_logger = "*"
log = "*"
clap = {version = "*", features = ["derive"] }
quinn = "*"
rustls = "*"
common = { path = "../common" }