[package]
name = "proxy-change-header"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "*",features = ["rt","macros","rt-multi-thread","io-util","net"]}
rweb-common = { path = "../rweb-common" }
log = "*"
simple_logger = "*"
clap = {version = "*", features = ["derive"] }