[lib]
name = "rwebc"
crate-type = ["cdylib"] 

[package]
name = "rwebc"
version = "0.1.0"
edition = "2024"

[features]
log = []

[dependencies]
tokio = {version = "1.44.2",features = ["rt","rt-multi-thread","time","io-util","net"]}
quinn = {version = "0.11.7",default-features = false,features = ["rustls-ring","runtime-tokio"]}
rustls = {version = "*"}
tokio-rustls = {version = "0.26.2"}
common = { path = "../common" }
url = "*"
once_cell = "*"
serde_json = {version = "*"}